stages:
  - build
  - deploy
  
build:
  image: maven:3.6.3-openjdk-11
  stage: build
  only:
  - master
  tags:
  - virtualize_backend
  script:
    - export c2c_db_url=$c2c_db_url
    - export c2c_db_username=$c2c_db_username
    - export c2c_db_pwd=$c2c_db_pwd
    - mvn clean package -B
  artifacts:
    paths:
      - target/
  when: manual
  
deploy_job:
  image: google/cloud-sdk:alpine
  stage: deploy
  only:
  - master
  tags:
  - virtualize_backend
  dependencies: 
    - build
  before_script:
  - "ServiceName=${CI_PROJECT_NAME/./-}"
  - "echo $ServiceName"
  - |
    cat <<EOF >> app.yaml
    runtime: java11
    env_variables:
      c2c_db_url: "$c2c_db_url"
      c2c_db_username: "$c2c_db_username"
      c2c_db_pwd: "$c2c_db_pwd"
    manual_scaling:
      instances: 1
    #liveness_check:
    #  path: "/test"
    #readiness_check:
    #  path: "/test"
    service: $ServiceName
    
    EOF
  - "cat app.yaml"
  - echo $GCP_SERVICE_CRED > ${CI_PIPELINE_ID}.json
 
  script:
  - gcloud auth activate-service-account --key-file $CI_PIPELINE_ID.json
  - gcloud --project hu18-groupa-java app deploy target/c2c-backend-0.0.1-SNAPSHOT.jar --appyaml app.yaml --version v1
  - url=$(gcloud app services browse $ServiceName --no-launch-browser --project hu18-groupa-java)
  - echo $url
  after_script:
  - rm $CI_PIPELINE_ID.json
  when: manual